### ISSUE TITLE
進行チャンネルのテキスト生成のところを改善

### ISSUE THREAD

**Issue by ca45382** [ca45382/shioriBotDotNet#114]
ここを修正してほしい。

https://github.com/ca45382/shioriBotDotNet/blob/ad128890bed0abfcf63ef71a1a22c7bc811e9fcb/Script/ClanBattle/BattleProgress.cs#L43-L50

**Comment by cllightz** [comment]
Discord.NET上のEmojiの実装を見ると
```cs
new Emoji(EnumMapper.I.GetString((ProgressStatus)ProgressData.Status)).Name
```
は
```cs
((ProgressStatus)ProgressData.Status).ToLabel()
```
と等価みたいですね

(Emojiのコンストラクタの引数がそのままNameに代入されている)
